Update patch set 1
Patch Set 1: Workflow-1

Ian Wienand wrote:

> It looks like this is unhappy:
>
>  AttributeError: 'TestNodepoolIntegration' object has no attribute
> 'config'

Yeah, the test class for this shadows the parent's setup method, so I need to forklift a bunch of config building from it.

Patch-set: 1
Reviewer: Gerrit User 5263 <5263@4a232e18-c5a9-48ee-94c0-e04e7cca6543>
Label: Workflow=-1