Fix getting Gerrit topic changes with git needs
Before getting a change by key we need to convert the reference to a
`ChangeKey` object.

Traceback (most recent call last):
  File "/opt/src/zuul/zuul/scheduler.py", line 2423, in process_tenant_trigger_queue
    self._forward_trigger_event(event, tenant)
  File "/opt/src/zuul/zuul/scheduler.py", line 2538, in _forward_trigger_event
    pipeline.manager.updateCommitDependencies(change, event)
  File "/opt/src/zuul/zuul/manager/__init__.py", line 924, in updateCommitDependencies
    for dep in source.getChangesByTopic(change.topic):
  File "/opt/src/zuul/zuul/driver/gerrit/gerritsource.py", line 171, in getChangesByTopic
    git_change = self.getChange(git_key)
  File "/opt/src/zuul/zuul/driver/gerrit/gerritsource.py", line 86, in getChange
    return self.connection.getChange(change_key, refresh=refresh,
  File "/opt/src/zuul/zuul/driver/gerrit/gerritconnection.py", line 791, in getChange
    if change_key.connection_name != self.connection_name:
AttributeError: 'str' object has no attribute 'connection_name'

Change-Id: I20663b538ccb48bc13191a134caf3326b6f5b76e