Pin CacheControl to <0.12.7
A recent update of CacheControl broke parts of the github api in zuul
which resulted in empty bodies in the response [1].

[1] Trace:
GET https://(...)/api/v3/(...)/files?per_page=100 result: 200, size: 0, duration: 67
ERROR zuul.GithubEventProcessor: Exception when processing event:
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.8/site-packages/github3/models.py", line 168, in _json
    ret = response.json()
  File "/opt/zuul/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zuul/lib/python3.8/site-packages/zuul/driver/github/githubconnection.py", line 346, in run
    self._process_event()
  File "/opt/zuul/lib/python3.8/site-packages/zuul/driver/github/githubconnection.py", line 404, in _process_event
    change = self.connection._getChange(
  File "/opt/zuul/lib/python3.8/site-packages/zuul/driver/github/githubconnection.py", line 1334, in _getChange
    pull = self.getPull(change.project.name, change.number,
  File "/opt/zuul/lib/python3.8/site-packages/zuul/driver/github/githubconnection.py", line 1706, in getPull
    pr['files'] = [f.filename for f in probj.files()]
  File "/opt/zuul/lib/python3.8/site-packages/zuul/driver/github/githubconnection.py", line 1706, in <listcomp>
    pr['files'] = [f.filename for f in probj.files()]
  File "/opt/zuul/lib/python3.8/site-packages/github3/structs.py", line 90, in __iter__
    json = self._get_json(response)
  File "/opt/zuul/lib/python3.8/site-packages/github3/structs.py", line 137, in _get_json
    return self._json(response, 200)
  File "/opt/zuul/lib/python3.8/site-packages/github3/models.py", line 170, in _json
    raise exceptions.UnexpectedResponse(response)
github3.exceptions.UnexpectedResponse: 200 [No message]

Change-Id: I5921e98d4252d4c96d116fe514b8637fad86a7fb