github: prevent AttributeError when missing branch protection
It seems like the _getBranchProtection should return an empty dictionary
to prevent:

Traceback (most recent call last):
  File "zuul/scheduler.py", line 883, in run
    self.process_event_queue()
  File "zuul/scheduler.py", line 952, in process_event_queue
    pipeline.manager.addChange(change)
  File "zuul/manager/__init__.py", line 236, in addChange
    if not self.isChangeReadyToBeEnqueued(change):
  File "zuul/manager/dependent.py", line 99, in isChangeReadyToBeEnqueued
    if not source.canMerge(change, self.getSubmitAllowNeeds()):
  File "zuul/driver/github/githubsource.py", line 59, in canMerge
    return self.connection.canMerge(change, allow_needs)
  File "zuul/driver/github/githubconnection.py", line 961, in canMerge
    required_reviews = protection.get(
AttributeError: 'NoneType' object has no attribute 'get'

Change-Id: Ia033da9feac98b28dcf09381fe0f90de76619927