Update patch set 5
Patch Set 5: Code-Review-1 -Workflow

After the rebase it fails with:

  Traceback (most recent call last):
    File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/tests/base.py", line 2447, in setUp
      self.sched.reconfigure(self.config)
    File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/scheduler.py", line 487, in reconfigure
      event.wait()
    File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/scheduler.py", line 60, in wait
      raise exception_instance.with_traceback(traceback)
    File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/scheduler.py", line 1053, in process_management_queue
      self._doReconfigureEvent(event)
    File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/scheduler.py", line 641, in _doReconfigureEvent
      self._get_project_key_dir())
    File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/configloader.py", line 1925, in loadConfig
      conf_tenant, old_tenant=None)
    File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/configloader.py", line 1344, in fromYaml
      tenant, parsed_config, loading_errors)
    File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/configloader.py", line 1865, in _parseLayout
      self._addLayoutItems(layout, tenant, data)
    File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/configloader.py", line 1761, in _addLayoutItems
      with reference_exceptions('pipeline', pipeline):
    File "/usr/lib/python3.5/contextlib.py", line 133, in helper
      return _GeneratorContextManager(func, args, kwds)
    File "/usr/lib/python3.5/contextlib.py", line 38, in __init__
      self.gen = func(*args, **kwds)
  TypeError: reference_exceptions() missing 1 required positional argument: 'accumulator'

Patch-set: 5
Label: Code-Review=-1