WIP: Fix implicit role for repos named ansible
When creating implicit roles we strip some common ansible
prefixes. However if the repo is named 'ansible' nothing is left and
we end up with an exception [1] when preparing the ansible run.

WIP because needs test

[1] Trace:
2018-04-11 15:11:29,601 DEBUG zuul.AnsibleJob: [build: eefa1daac14348c88cad40da7e1a0748] Prepare zuul role for {'target_name': '', 'type': 'zuul', 'connection': 'github', 'project': 'example/ansible', 'implicit': True}
2018-04-11 15:11:29,602 ERROR zuul.AnsibleJob: [build: eefa1daac14348c88cad40da7e1a0748] Exception while executing job
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/zuul/executor/server.py", line 632, in execute
    self._execute()
  File "/usr/lib/python3.6/site-packages/zuul/executor/server.py", line 744, in _execute
    self.preparePlaybooks(args)
  File "/usr/lib/python3.6/site-packages/zuul/executor/server.py", line 1110, in preparePlaybooks
    self.preparePlaybook(jobdir_playbook, playbook, args)
  File "/usr/lib/python3.6/site-packages/zuul/executor/server.py", line 1165, in preparePlaybook
    self.prepareRole(jobdir_playbook, role, args)
  File "/usr/lib/python3.6/site-packages/zuul/executor/server.py", line 1193, in prepareRole
    self.prepareZuulRole(jobdir_playbook, role, args, root)
  File "/usr/lib/python3.6/site-packages/zuul/executor/server.py", line 1253, in prepareZuulRole
    os.symlink(path, link)
FileExistsError: [Errno 17] File exists: '/tmp/eefa1daac14348c88cad40da7e1a0748/work/src/github/example/ansible' -> '/tmp/eefa1daac14348c88cad40da7e1a0748/ansible/playbook_0/role_0'

Change-Id: Ie28688e2e30222d2a146e9bdb4870f63ecece239