Ensure build.start_time is defined
When a build failed with NOT_REGISTERED or RETRY_LIMIT, the onBuildStarted
method isn't called, resulting in the sql reporter failing with:

Traceback (most recent call last):
  File "zuul/scheduler.py", line 1774, in _reportItem
    ret = self.sendReport(actions, self.pipeline.source, item)
  File "zuul/scheduler.py", line 1298, in sendReport
    ret = reporter.report(source, self.pipeline, item)
  File "zuul/reporter/sql.py", line 92, in report
    build.start_time),
TypeError: a float is required

Change-Id: I4f79e4bc48e81b3ae21111723084f65642c040c2