web: angular6 fix suggestion
This change fix some angular bits to fix deployment in software-factory:

* call enableProdMode() and manually disable router Tracing (i couldn't call
  enableProdMode because of the isDevMode() call, it fails with:
    Error: Cannot enable prod mode after platform setup.)
* Fix navbar being displayed on tenants listing page.
* Fix tenants list link.
* Fix getSourceUrl for sub-path zuul-web api deployment.

Change-Id: Id1f9d89b9de11c8d7680355a57b7316bd456c6c2