Don't abort supercedent processing on cycle
When e.g. a Github PR that has a circular dependency is closed (but not
merged), supercedent pipelines will throw the below execption when the
event is processed, which will abort this pipeline progessing run.

This can happen even if the pipeline requires a PR to be merged (via the
pipeline requirement. The reason for this is that resolving the cycle
happens before the pipeline requirements are checked.

ERROR zuul.Scheduler: Exception processing pipeline post in tenant foobar
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.11/site-packages/zuul/scheduler.py", line 2279, in process_pipelines
    refreshed = self._process_pipeline(
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/scheduler.py", line 2360, in _process_pipeline
    self.process_pipeline_trigger_queue(tenant, pipeline)
  File "/opt/zuul/lib/python3.11/site-packages/zuul/scheduler.py", line 2596, in process_pipeline_trigger_queue
    self._process_trigger_event(tenant, pipeline, event)
  File "/opt/zuul/lib/python3.11/site-packages/zuul/scheduler.py", line 2629, in _process_trigger_event
    pipeline.manager.addChange(change, event)
  File "/opt/zuul/lib/python3.11/site-packages/zuul/manager/supercedent.py", line 79, in addChange
    ret = super(SupercedentPipelineManager, self).addChange(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/manager/__init__.py", line 611, in addChange
    cycle = self.cycleForChange(change, dependency_graph, event)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/manager/supercedent.py", line 74, in cycleForChange
    raise Exception("Dependency cycles not supported "
Exception: Dependency cycles not supported in supercedent pipelines

Change-Id: I3bc85ae9e94e8dd08ea30380c724778046b1ec23