Disable Log Streaming from k8s Pod Nodes
Temporarily disable log streaming from k8s Pod nodes because of bugous
kubectl port-forwading.
While streaming the output from command/shell tasks from k8s Pods, the
TCP connection gets reset sporadically leading to missing log output and
a 30 sec time penalty.

The error that appears sporadically is
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/var/lib/zuul/ansible/2.9/zuul/ansible/callback/zuul_stream.py", line 161, in _read_log
    buff = s.recv(4096)
ConnectionResetError: [Errno 105] Connection reset by peer
```
and might be related to the k8s upstream issue here
https://github.com/kubernetes/kubernetes/issues/74551

Change-Id: I0edd43604fab16ac79300b9729fe97a69d86170c