Fix exception when using enqueue-ref (gitlab test)
When running test_gitlab_driver test_client_enqueue_ref, event.branch
being not set (value is None) leads to the following exception:

Traceback (most recent call last):
  File "/home/testzuul/zuul/zuul/zuul/scheduler.py", line 1436, in _doBuildStartedEvent
    build.estimated_time = float(self.time_database.getEstimatedTime(
  File "/home/testzuul/zuul/zuul/zuul/model.py", line 4745, in getEstimatedTime
    return self._getTD(name).getEstimatedTime()
  File "/home/testzuul/zuul/zuul/zuul/model.py", line 4731, in _getTD
    dir_path = os.path.join(
  File "/usr/lib/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.8/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

When we can identify as much as possible the ref as a branch, set
event.branch. This change fixes such exception

Change-Id: I50e483ab3000bf4ac51f3c1d47f54f0797b29d03