Ignore soft dependencies when getting parent jobs
This fixes a bug in model API <= 20 legacy implementation to get parent
jobs recursively. This leads to pipeline processing to be aborted when
hitting this edge case.

Traceback (most recent call last):
  File "/opt/zuul/lib/python3.11/site-packages/zuul/scheduler.py", line 2362, in _process_pipeline
    while not self._stopped and pipeline.manager.processQueue():
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/manager/__init__.py", line 1882, in processQueue
    item_changed, nnfi = self._processOneItem(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/manager/__init__.py", line 1740, in _processOneItem
    ready = self.prepareItem(item)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/manager/__init__.py", line 1625, in prepareItem
    while item.deduplicateJobs(log):
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/model.py", line 5886, in deduplicateJobs
    self.updateJobParentData()
  File "/opt/zuul/lib/python3.11/site-packages/zuul/model.py", line 5790, in updateJobParentData
    for parent_job in job_graph.getParentJobsRecursively(job):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/model.py", line 3845, in getParentJobsRecursively
    self._legacyGetParentJobNamesRecursively(
  File "/opt/zuul/lib/python3.11/site-packages/zuul/model.py", line 3891, in _legacyGetParentJobNamesRecursively
    raise Exception("Job %s depends on %s which was not run." %
Exception: Job child depends on soft-parent which was not run.

Change-Id: Ia60e7f95fbde775fcc8dfe7d60f720753473d6e3