Initialize missing pipeline change list attribute
If a scheduler with a freshly initialized PipelineChangeList object
(after a reconfig) fails to update the change list before forwarding
trigger events, it will also fail to forward the event as the
`_change_keys` field was only initialized after a successful refresh.

Traceback (most recent call last):
  File "/opt/zuul/lib/python3.10/site-packages/zuul/scheduler.py", line 2309, in process_tenant_trigger_queue
    self._forward_trigger_event(event, tenant)
  File "/opt/zuul/lib/python3.10/site-packages/zuul/scheduler.py", line 2410, in _forward_trigger_event
    or pipeline.manager.isAnyVersionOfChangeInPipeline(change)
  File "/opt/zuul/lib/python3.10/site-packages/zuul/manager/__init__.py", line 263, in isAnyVersionOfChangeInPipeline
    for change_key in self.pipeline.change_list.getChangeKeys():
  File "/opt/zuul/lib/python3.10/site-packages/zuul/model.py", line 951, in getChangeKeys
    return self._change_keys
AttributeError: 'PipelineChangeList' object has no attribute '_change_keys'

Set the `_change_keys` attribute in the init so we don't fail to forward
the event to all pipelines.

Change-Id: Iadb5e502bfd135a9e06dc871191979c88ed9d455