WIP: Fix scheduler breakage when using periodic jobs with artifacts
TODO:
- Tests

The artifacts code doesn't work when the change has no number (e.g. is
a branch) which kicks zuul out of the run_handler [1]. The only way to
recover is a scheduler restart or a dequeue of the causing item.

[1] Trace:
2019-05-15 06:31:34,015 ERROR zuul.Scheduler: Exception in run handler:
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.7/site-packages/zuul/scheduler.py", line 1062, in run
    while (pipeline.manager.processQueue() and
  File "/opt/zuul/lib/python3.7/site-packages/zuul/manager/__init__.py", line 788, in processQueue
    item, nnfi)
  File "/opt/zuul/lib/python3.7/site-packages/zuul/manager/__init__.py", line 744, in _processOneItem
    if ready and self.executeJobs(item):
  File "/opt/zuul/lib/python3.7/site-packages/zuul/manager/__init__.py", line 417, in executeJobs
    item.pipeline.tenant.semaphore_handler)
  File "/opt/zuul/lib/python3.7/site-packages/zuul/model.py", line 2450, in findJobsToRun
    job.updateParentData(parent_build)
  File "/opt/zuul/lib/python3.7/site-packages/zuul/model.py", line 1437, in updateParentData
   'change': str(change.number),
AttributeError: 'Branch' object has no attribute 'number'

Change-Id: I418ae381ef5c1e5d115fc3e0f6cc490077762887