Fix manual dequeue of github items
Currently dequeuing a github item fails with [1]. This is caused
because the DequeueEvent has no change_url attribute. In order to fix
this we need to add a check and add the correct change_url if it
doesn't exist. This by accident fixes a second issue where manually
enqueued github items miss the change_url.

This adds a fix and test case for both use cases.

[1] Traceback:
2018-11-21 14:17:56,592 ERROR zuul.Scheduler: Exception in management event:
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.6/site-packages/zuul/scheduler.py", line 1096, in process_management_queue
    self._doDequeueEvent(event)
  File "/opt/zuul/lib/python3.6/site-packages/zuul/scheduler.py", line 917, in _doDequeueEvent
    change = project.source.getChange(event, project)
  File "/opt/zuul/lib/python3.6/site-packages/zuul/driver/github/githubsource.py", line 66, in getChange
    return self.connection.getChange(event, refresh)
  File "/opt/zuul/lib/python3.6/site-packages/zuul/driver/github/githubconnection.py", line 789, in getChange
    change.url = event.change_url
AttributeError: 'DequeueEvent' object has no attribute 'change_url'

Change-Id: Ifbaa67dc06c671f9235545a3215aa337ab27697e