Fix exception in blob store cleanup
Return early when a QueueItem doesn't have a job graph to avoid
exceptions during blob store cleanup.

2022-06-29 09:07:26,908 ERROR zuul.Scheduler: Error in blob store cleanup:
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.8/site-packages/zuul/scheduler.py", line 753, in _runBlobStoreCleanup
    live_blobs.update(item.getBlobKeys())
  File "/opt/zuul/lib/python3.8/site-packages/zuul/model.py", line 5250, in getBlobKeys
    for job in job_graph.getJobs():
AttributeError: 'NoneType' object has no attribute 'getJobs'

Change-Id: I443e1fe2240d0fd7fdcabc174078062a2a20058a