WIP NodeRequest watches
The purpose of this change is to replace the update mechanism of local
node requests with data watches in ZooKeeper. If we want to have a
multi-scheduler setup we cannot rely on local node request objects
anymore as one scheduler could submit the request while another handles
the fulfillment of the same request.

Notable change: Empty node requests are now also stored in ZooKeeper
(directly with state = fulfilled).

Open points:

  1. The local node request objects are still stored in
     build_set.node_requests. The objects in this dictionary might not
     reflect the current state of the node request, so we have to find a
     way to either keep them in sync with the node requests in ZK or to
     only store the node request ids in that dictionary and look the
     node requests up from ZK when needed. This should work for all
     cases where build_set.node_requests is used, except one case in the
     pipeline manager where this might produce a lot of I/O in
     ZooKeeper [1].

     => We decided to enhance the node request data watches with a cache
     so that every scheduler has a local representation of all node
     requests in the system (same like for the executor and merger api).
     As the nodepool implementation is using a similar data watch
     implementation it should be easy to add such a dictionary.
     NOTE: The leader election (point 3.) should still be done for
     submitting the node provisioned events. So, all schedulers update
     their local node request cache via data watches, but only one
     scheduler will submit node provisioned events.

  2. As the node request is now taken from ZK directly whenever a data
     watch is invoked, we have to provide additional information to
     fully restore the nodeset from the information stored in ZK. This
     includes the node names and groups. This is necessary as we are not
     relying on the local node request objects anymore when handling the
     nodes provisioned event (and providing the node information via
     parameters to the build), but use the node request stored in ZK.
     The current version of this change stores those values in the
     requestor_data field, but that doesn't feel like a proper solution
     and more like a workaround.

     => We decided to move the nodeset out of the node request object as
     the node request is mainly about node labels, and the nodeset is
     something that only Zuul knows about. We should look up the
     original nodeset information (like node names and groups) from the
     frozen job and hydrate it with the node data from ZooKeeper when
     necessary (e.g. when the build request is created in the executor
     client).
     We could then also remove the "node update" part in
     zuul.zk.nodepool.getNodeRequest() which should also spare some ZK
     operations if the nodes are not needed.

       * This is now done in a parent change.

  3. The node request event callback should be wrapped by a leader
     election, so that only one scheduler puts new
     NodesProvisionedEvents in the pipeline result event queue.

     => When a new leader is elected, it has to iterate over all
     unlocked node requests and submit a nodes provisioned event for
     each one that is fulfilled. Otherwise we might be missing events if
     a node request was fulfilled while the leader changed. This is also
     the reason for point 4. as there might be multiple nodes
     provisioned events for the same node request and the pipeline
     manager has to filter those out.

  4. The pipeline manager should be able to deal with multiple
     NodesProvisionedEvents being submitted for the same NodeRequest as
     a DataWatch might be invoked multiple times while the node request
     is in state fulfilled (which is the indicator to create a
     NodesProvisionedEvent). I saw the following exception ones in a
     test, not sure if that is a proper indicator for that or something
     else:

        ERROR    Exception in run handler:
        Traceback (most recent call last):
          File "/workspace/zuul/scheduler.py", line 1521, in run
            self.process_pipelines(tenant)
          File "/workspace/zuul/scheduler.py", line 1567, in process_pipelines
            self._process_pipeline(tenant, pipeline)
          File "/workspace/zuul/scheduler.py", line 1577, in _process_pipeline
            self.process_pipeline_result_queue(tenant, pipeline)
          File "/workspace/zuul/scheduler.py", line 1834, in process_pipeline_result_queue
            self._process_result_event(event, pipeline)
          File "/workspace/zuul/scheduler.py", line 1855, in _process_result_event
            self._doNodesProvisionedEvent(event, pipeline)
          File "/workspace/zuul/scheduler.py", line 2093, in _doNodesProvisionedEvent
            pipeline.manager.onNodesProvisioned(request, build_set)
          File "/workspace/zuul/manager/__init__.py", line 1508, in onNodesProvisioned
            build_set.jobNodeRequestComplete(request.job_name, request.nodeset)
          File "/workspace/zuul/model.py", line 2490, in jobNodeRequestComplete
            raise Exception("Prior node request for %s" % (job_name))
        Exception: Prior node request for project-test1

  5. Provide a system id (uuid for the whole Zuul deployment) to the
     node request (most probably in the requestor_data field), so that
     Zuul only creates data watches for its own node requests and
     ignores the ones that nodepool submits for itself (I think there is
     something like this).

       * The uuid now exists in a parent change.

[1]: https://opendev.org/zuul/zuul/src/branch/master/zuul/manager/__init__.py#L1302

Change-Id: I8b976a333b7de3bca3feb7a7496195aab5b034fd