Fix exceptions on reconfig with changing window
When the window size changes, items formerly in the window might be no
longer active. But those items can already have build results. During
reconfiguration the job graph is set to None, but the item is not
prepared if no longer active. This becomes problematic when
build.setResult() tries to access the job graph when resetting builds.

This can be solved by also preparing the item if there was already a job
graph. The other option to fix this, would be to never change the
item.active state back to False after it became active. However, this
would be a change in the current behavior of Zuul, as only as builds
finish the active window would actually decrease.

Exceptions:

2019-12-03 08:11:06,298 zuul.Scheduler ERROR Exception while re-enqueing item <QueueItem 0x7f54285a49b0 for <Change 0x7f5442939da0 org/project 4,1> in gate>
Traceback (most recent call last):
  File "/tmp/zuul/zuul/scheduler.py", line 931, in _reenqueueTenant
    item_ahead_valid=item_ahead_valid)
  File "/tmp/zuul/zuul/manager/__init__.py", line 276, in reEnqueueItem
    item.setResult(build)
  File "/tmp/zuul/zuul/model.py", line 2642, in setResult
    to_skip = self.job_graph.getDependentJobsRecursively(
AttributeError: 'NoneType' object has no attribute 'getDependentJobsRecursively'

2019-12-03 08:11:11,401 zuul.Scheduler ERROR Exception in run handler:
Traceback (most recent call last):
  File "/tmp/zuul/zuul/scheduler.py", line 1133, in run
    self.process_result_queue()
  File "/tmp/zuul/zuul/scheduler.py", line 1268, in process_result_queue
    self._doBuildCompletedEvent(event)
  File "/tmp/zuul/zuul/scheduler.py", line 1473, in _doBuildCompletedEvent
    pipeline.manager.onBuildCompleted(event.build)
  File "/tmp/zuul/zuul/manager/__init__.py", line 995, in onBuildCompleted
    item.setResult(build)
  File "/tmp/zuul/zuul/model.py", line 2642, in setResult
    to_skip = self.job_graph.getDependentJobsRecursively(
AttributeError: 'NoneType' object has no attribute 'getDependentJobsRecursively'

Change-Id: I96d4b28a017a1371029ff7b8d516beb09b6b94ad