Ignore non-serializable objects in JobData
The JobData's `serialize()` method used the `json.dumps()` method from
the standard library instead of the Zuul specific `json_dumps()` helper
that ignores the non-serializable objects.

Traceback (most recent call last):
  File "/opt/zuul/lib/python3.8/site-packages/zuul/manager/__init__.py", line 1303, in prepareItem
    item.freezeJobGraph(self.getLayout(item),
  File "/opt/zuul/lib/python3.8/site-packages/zuul/model.py", line 4157, in freezeJobGraph
    job_graph = layout.createJobGraph(
  File "/opt/zuul/lib/python3.8/site-packages/zuul/model.py", line 7151, in createJobGraph
    self._createJobGraph(context, item, ppc, job_graph,
  File "/opt/zuul/lib/python3.8/site-packages/zuul/model.py", line 7134, in _createJobGraph
    job_graph.addJob(frozen_job.freezeJob(
  File "/opt/zuul/lib/python3.8/site-packages/zuul/model.py", line 2504, in freezeJob
    return FrozenJob.new(context, **kw)
  File "/opt/zuul/lib/python3.8/site-packages/zuul/model.py", line 2002, in new
    update_kw['_' + k] = obj._makeJobData(context, k, v)
  File "/opt/zuul/lib/python3.8/site-packages/zuul/model.py", line 2212, in _makeJobData
    return JobData.new(
  File "/opt/zuul/lib/python3.8/site-packages/zuul/model.py", line 1903, in new
    data = obj._trySerialize(context)
  File "/opt/zuul/lib/python3.8/site-packages/zuul/zk/zkobject.py", line 159, in _trySerialize
    return self.serialize()
  File "/opt/zuul/lib/python3.8/site-packages/zuul/model.py", line 1920, in serialize
    return json.dumps(data, sort_keys=True).encode("utf8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SourceContext is not JSON serializable

Change-Id: If698f475ebb7e1fbed9bb69fd92c6629d668d18e