Handle artifacts created by non change refs
Artifact processing assumed that there would always be a change number
and patchset associated with the build producing an artifact. If
Artifacts are generated by jobs triggered by refs/branch/tag events then
this is not the case and it results in an exception like this:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.11/site-packages/zuul/manager/__init__.py", line 1065, in _executeJobs
      self.sched.executor.execute(
    File "/usr/local/lib/python3.11/site-packages/zuul/executor/client.py", line 63, in execute
      params = zuul.executor.common.construct_build_params(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/zuul/executor/common.py", line 97, in construct_build_params
      ) = item.getJobParentData(job)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/zuul/model.py", line 5431, in getJobParentData
      artifact_data = job.artifact_data or self.getArtifactData(job)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/zuul/model.py", line 5414, in getArtifactData
      self.providesRequirements(job, data)
    File "/usr/local/lib/python3.11/site-packages/zuul/model.py", line 5377, in providesRequirements
      'change': change.number,
                ^^^^^^^^^^^^^
  AttributeError: 'Tag' object has no attribute 'number'

Address this by checking if that artifact has a change number and
patchset and if not we associate the ref, oldrev, and newrev with the
artifact instead of the change number and patchset.

Change-Id: I5ba7f30e56fc890847b86ee776e74272ec04046d