Don't rely on statsd client in zuul times library
Currently, the following exception is raised in a lot of test cases,
because the statsd section is missing in the test-specific config
files:

  Traceback (most recent call last):
    File "/workspace/zuul/lib/times.py", line 66, in run
      with self.statsd.timer('zuul.scheduler.time_query'):
  AttributeError: 'NoneType' object has no attribute 'timer'

Instead of adding the section to all files, we could change the code to
not rely on the statsd client in this case.

Change-Id: I9d042d91e0e1c9169197e43ee1536aeff16ced07