Fix secrets overwritten in deduplicate secrets
In the case if a secret name is used in parent job and child job with
different secrets, they can overwrite each other. One of them would be
missing in the secrets list, thus causing exception in resolving the
index of it.

A sample traceback:
```
raceback (most recent call last):
  File "/opt/zuul/lib/python3.11/site-packages/zuul/manager/__init__.py", line 1545, in prepareItem
    item.freezeJobGraph(self.getLayout(item),
  File "/opt/zuul/lib/python3.11/site-packages/zuul/model.py", line 5106, in freezeJobGraph
    job_graph = layout.createJobGraph(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/model.py", line 8507, in createJobGraph
    self._createJobGraph(context, item, ppc, job_graph,
  File "/opt/zuul/lib/python3.11/site-packages/zuul/model.py", line 8490, in _createJobGraph
    job_graph.addJob(frozen_job.freezeJob(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/model.py", line 3003, in freezeJob
    kw['secrets'] = self._deduplicateSecrets(context, frozen_playbooks)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/model.py", line 2949, in _deduplicateSecrets
    playbook['secrets'][secret_key] = resolver(secrets)
                                      ^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/model.py", line 2919, in _resolve_index
    return secrets.index(secret_value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: {'connection_name': ‚connectionx, 'project_name': ‚org/repo, 'encrypted_data': 'key: !encrypted/pkcs1-oaep\n- *****‘} is not in list
```

Change-Id: Iebe6d7b716602438499151784278c3505a022429