Fix Gerrit change query retry exceeded
The change query method in the Gerrit driver had a bug in that it could
return None when all query attempts failed instead of raising an
exception. This could lead to execeptions during event processing but
also break pipeline processing:

ERROR zuul.GerritEventConnector: Exception moving Gerrit event:
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.11/site-packages/zuul/driver/gerrit/gerritconnection.py", line 239, in run
    self.event_queue.election.run(self._run)
  File "/opt/zuul/lib/python3.11/site-packages/zuul/zk/election.py", line 28, in run
    return super().run(func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/kazoo/recipe/election.py", line 54, in run
    func(*args, **kwargs)
  File "/opt/zuul/lib/python3.11/site-packages/zuul/driver/gerrit/gerritconnection.py", line 261, in _run
    self._handleEvent(event)
  File "/opt/zuul/lib/python3.11/site-packages/zuul/driver/gerrit/gerritconnection.py", line 313, in _handleEvent
    change = self._getChange(event, connection_event.zuul_event_ltime)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/driver/gerrit/gerritconnection.py", line 360, in _getChange
    change = self.connection._getChange(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/driver/gerrit/gerritconnection.py", line 643, in _getChange
    return self._updateChange(change_key, change, event, history,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/driver/gerrit/gerritconnection.py", line 786, in _updateChange
    change.update(data, {}, self)
  File "/opt/zuul/lib/python3.11/site-packages/zuul/driver/gerrit/gerritmodel.py", line 46, in update
    self.zuul_query_ltime = data.zuul_query_ltime
                            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'zuul_query_ltime'

ERROR zuul.source.Gerrit: Failed to retrieve dependency https://gerrit.foobar/+/123. Retrying
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.11/site-packages/zuul/source/__init__.py", line 100, in getChangeByURLWithRetry
    return self.getChangeByURL(url, event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/driver/gerrit/gerritsource.py", line 122, in getChangeByURL
    change = self.connection._getChange(change_key, event=event)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/driver/gerrit/gerritconnection.py", line 643, in _getChange
    return self._updateChange(change_key, change, event, history,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/driver/gerrit/gerritconnection.py", line 786, in _updateChange
    change.update(data, {}, self)
  File "/opt/zuul/lib/python3.11/site-packages/zuul/driver/gerrit/gerritmodel.py", line 46, in update
    self.zuul_query_ltime = data.zuul_query_ltime
                            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'zuul_query_ltime'

ERROR zuul.Scheduler: Exception in pipeline processing:
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.11/site-packages/zuul/scheduler.py", line 2380, in _process_pipeline
    while not self._stopped and pipeline.manager.processQueue(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/manager/__init__.py", line 2019, in processQueue
    item_changed, nnfi = self._processOneItem(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/manager/__init__.py", line 1967, in _processOneItem
    self.reportItem(item)
  File "/opt/zuul/lib/python3.11/site-packages/zuul/manager/__init__.py", line 2333, in reportItem
    merged = source.isMerged(change, change.branch)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/driver/gerrit/gerritsource.py", line 58, in isMerged
    return self.connection.isMerged(change, head)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/driver/gerrit/gerritconnection.py", line 911, in isMerged
    self._change_cache.updateChangeWithRetry(key, change, _update_change)
  File "/opt/zuul/lib/python3.11/site-packages/zuul/zk/change_cache.py", line 434, in updateChangeWithRetry
    newkey = update_func(change)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/zuul/driver/gerrit/gerritconnection.py", line 909, in _update_change
    c.update(data, {}, self)
  File "/opt/zuul/lib/python3.11/site-packages/zuul/driver/gerrit/gerritmodel.py", line 46, in update
    self.zuul_query_ltime = data.zuul_query_ltime
                            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'zuul_query_ltime'

Change-Id: Ibfbc1c0e627099d58f4c3a80327cb9820be4341b