Update patch set 24
Patch Set 24: Code-Review-1

So we probably don't want to lose minimize or turn on debugging so I'm guessing this was a test patchset.

FWIW it appears to be working except for log streaming:

"TypeError: a.getSourceUrl is not a function".

Patch-set: 24
Label: Code-Review=-1