Prevent MR message to be None in order to be process by the scheduler
When a MR is not created via the GitLab webui (via the API for instance) then
the MR description might be unset resulting being None and then cannot be processed:

2021-11-03 08:40:54,585 INFO zuul.GitlabConnection: Getting change for redhat/centos-stream/rpms/dovecot#17
2021-11-03 08:40:54,590 ERROR zuul.Scheduler: Exception in run handler:
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/zuul/scheduler.py", line 1265, in run
self.process_trigger_queue()
File "/usr/lib/python3.6/site-packages/zuul/scheduler.py", line 1396, in process_trigger_queue
self._process_trigger_event(tenant, pipeline, event)
File "/usr/lib/python3.6/site-packages/zuul/scheduler.py", line 1422, in _process_trigger_event
pipeline.manager.addChange(change, event)
File "/usr/lib/python3.6/site-packages/zuul/manager/_init_.py", line 388, in addChange
dependency_graph=dependency_graph):
File "/usr/lib/python3.6/site-packages/zuul/manager/independent.py", line 51, in enqueueChangesAhead
dependency_graph=dependency_graph)
File "/usr/lib/python3.6/site-packages/zuul/manager/independent.py", line 81, in checkForChangesNeededBy
self.updateCommitDependencies(change, None, event)
File "/usr/lib/python3.6/site-packages/zuul/manager/_init_.py", line 597, in updateCommitDependencies
for match in find_dependency_headers(change.message):
File "/usr/lib/python3.6/site-packages/zuul/lib/dependson.py", line 25, in find_dependency_headers
for match in DEPENDS_ON_RE.findall(message):
TypeError: expected string or bytes-like object

This change ensures that a MR message is at least an empty string.

Change-Id: Ia7564120e79093db20212d6fb37ccf262bd2f2b7