Handle unicode (or high bytes) coming from output
We see this:

  File "/var/lib/zuul/ansible/zuul/ansible/callback/zuul_stream.py", line 139, in _read_log
    self._log("%s | %s " % (host, ln), ts=ts)
  File "/var/lib/zuul/ansible/zuul/ansible/callback/zuul_stream.py", line 111, in _log
    self._logger.info("{now} | {msg}".format(now=now, msg=msg))
  UnicodeEncodeError: 'ascii' codec can't encode character u'\\u011f' in position 64: ordinal not in range(128)

It's possible that we actually need to be handling utf-8 hand-off with
the remote log streamer though.

Change-Id: I71a16813092b01637db7aba651a913b8f4cb22b2