WIP NodeRequest watches
Notable change: Empty node requests are now also stored in ZooKeeper
(directly with state = fulfilled).

Open points:

  1. The local node request objects are still stored in
     build_set.node_requests. The objects in this dictionary might not
     reflect the current state of the node request, so we have to find a
     way to either keep them in sync with the node requests in ZK or to
     only store the node request ids in that dictionary and look the
     node requests up from ZK when needed. This should work for all
     cases where build_set.node_requests is used, except one case in the
     pipeline manager where this might produce a lot of I/O in
     ZooKeeper [1].

  2. As the node request is now taken from ZK directly whenever a data
     watch is invoked, we have to provide additional information to
     fully restore the nodeset from information stored in ZK. This
     includes the node names and groups. This is necessary as we are not
     relying on the local node request objects anymore when handling the
     nodes provisioned event (and providing the node information via
     parameters to the build), but use the node request stored in ZK. By
     default, the node request data structure in ZK only provides the
     node labels, but not the names and groups. Without those
     information stored in ZK, we are not able to provide them to the
     build (e.g. inventory.yaml). The current version of this change
     stores those values in the requestor_data field, but that doesn't
     feel like a proper solution and more like a workaround.

  3. The node request event callback should be wrapped by a leader
     election, so that only one scheduler puts new
     NodesProvisionedEvents in the pipeline result event queue.

  4. The pipeline manager should be able to deal with multiple
     NodesProvisionedEvents being submitted for the same NodeRequest as
     a DataWatch might be invoked multiple times while the node request
     is in state fulfilled (which is the indicator to create a
     NodesProvisionedEvent). I saw the following exception ones in a
     test, not sure if that is a proper indicator for that or something
     else:

        ERROR    Exception in run handler:
        Traceback (most recent call last):
          File "/workspace/zuul/scheduler.py", line 1521, in run
            self.process_pipelines(tenant)
          File "/workspace/zuul/scheduler.py", line 1567, in process_pipelines
            self._process_pipeline(tenant, pipeline)
          File "/workspace/zuul/scheduler.py", line 1577, in _process_pipeline
            self.process_pipeline_result_queue(tenant, pipeline)
          File "/workspace/zuul/scheduler.py", line 1834, in process_pipeline_result_queue
            self._process_result_event(event, pipeline)
          File "/workspace/zuul/scheduler.py", line 1855, in _process_result_event
            self._doNodesProvisionedEvent(event, pipeline)
          File "/workspace/zuul/scheduler.py", line 2093, in _doNodesProvisionedEvent
            pipeline.manager.onNodesProvisioned(request, build_set)
          File "/workspace/zuul/manager/__init__.py", line 1508, in onNodesProvisioned
            build_set.jobNodeRequestComplete(request.job_name, request.nodeset)
          File "/workspace/zuul/model.py", line 2490, in jobNodeRequestComplete
            raise Exception("Prior node request for %s" % (job_name))
        Exception: Prior node request for project-test1

[1]: https://opendev.org/zuul/zuul/src/branch/master/zuul/manager/__init__.py#L1302

Change-Id: I8b976a333b7de3bca3feb7a7496195aab5b034fd