Don't check branch cache when project not in min. ltimes
ERROR zuul.TenantParser: Min. ltime missing for project/branch
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.10/site-packages/zuul/configloader.py", line 2176, in _cacheTenantYAMLBranch
    pb_ltime = min_ltimes[project.canonical_name][branch]
KeyError: 'github.com/org/project'

Change-Id: Ie63cbb55b194f35e1ea212b2111caa4a5792f5f0