Add missing timestamp to change mgmt events
As change management events (e.g. enqueue) will be attached as
triggering events to queue items we need to make sure they have a
timestamp set as some reporters rely on that attribute.

2021-06-17 05:31:40,553 ERROR zuul.MQTTReporter: Exception processing report item
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.8/site-packages/zuul/reporter/__init__.py", line 76, in doReport
    ret = self.report(item)
  File "/opt/zuul/lib/python3.8/site-packages/zuul/driver/mqtt/mqttreporter.py", line 49, in report
    'trigger_time': item.event.timestamp,
AttributeError: 'EnqueueEvent' object has no attribute 'timestamp'

Change-Id: I89dfd2bbeef4604e088bda2998b2be74e7413fc3