Fix zuul startup with inexisting project template and gate
When there is a dependent pipeline in a tenant that has a reference to
a non-existing project template zuul fails to start with [1]. However
it should be able to start and instead report this as a loading error.

This is caused by the pipeline postprocessing which safely can be
skipped if there are loading errors.

[1] Trace:
2018-07-02 05:19:19,359 ERROR zuul.Scheduler: Exception in management event:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/zuul/scheduler.py", line 988, in process_management_queue
    self._doReconfigureEvent(event)
  File "/usr/lib/python3.6/site-packages/zuul/scheduler.py", line 588, in _doReconfigureEvent
    self._get_project_key_dir())
  File "/usr/lib/python3.6/site-packages/zuul/configloader.py", line 1876, in loadConfig
    conf_tenant, old_tenant=None)
  File "/usr/lib/python3.6/site-packages/zuul/configloader.py", line 1298, in fromYaml
    tenant, parsed_config, loading_errors)
  File "/usr/lib/python3.6/site-packages/zuul/configloader.py", line 1819, in _parseLayout
    pipeline.manager._postConfig(layout)
  File "/usr/lib/python3.6/site-packages/zuul/manager/dependent.py", line 33, in _postConfig
    self.buildChangeQueues()
  File "/usr/lib/python3.6/site-packages/zuul/manager/dependent.py", line 46, in buildChangeQueues
    for project_config in layout.getAllProjectConfigs(project_name):
  File "/usr/lib/python3.6/site-packages/zuul/model.py", line 3018, in getAllProjectConfigs
    templates = self.getProjectTemplates(template_name)
  File "/usr/lib/python3.6/site-packages/zuul/model.py", line 2992, in getProjectTemplates
    raise Exception("Project template %s not found" % name)
Exception: Project template foo not found

Change-Id: Ib26eb1476ffd212ab766eb151175ade8109dae45