Add default value for relative_priority
If we don't do so we get this error reading from model when there is no
relative_priority attribute at zuul.conf

  File "/usr/local/lib/python3.7/site-packages/zuul/model.py", line 752,
in updateFromDict
    self.relative_priority = data['relative_priority']
KeyError: 'relative_priority'

Change-Id: I68e958b87072bed671c9b1efd2e9e3a20f700ec4