Add missing attributes to Gitlab MergeRequest
Currently, when a Gitlab MergeRequest is freshly deserialized from
ZooKeeper, it is missing the 'merge_status' attribute, which causes the
run handler to fail processing this change:

  Traceback (most recent call last):
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/scheduler.py", line 1643, in run
      self.process_pipelines(tenant)
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/scheduler.py", line 1698, in process_pipelines
      self._process_pipeline(tenant, pipeline)
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/scheduler.py", line 1710, in _process_pipeline
      self.process_pipeline_trigger_queue(tenant, pipeline)
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/scheduler.py", line 1852, in process_pipeline_trigger_queue
      self._process_trigger_event(tenant, pipeline, event)
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/scheduler.py", line 1884, in _process_trigger_event
      pipeline.manager.addChange(change, event)
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/manager/__init__.py", line 477, in addChange
      if not self.isChangeReadyToBeEnqueued(change, event):
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/manager/dependent.py", line 53, in isChangeReadyToBeEnqueued
      if not source.canMerge(change, self.getSubmitAllowNeeds(),
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/driver/gitlab/gitlabsource.py", line 54, in canMerge
      return self.connection.canMerge(change, allow_needs, event=event)
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/driver/gitlab/gitlabconnection.py", line 659, in canMerge
      can_merge = True if change.merge_status == "can_be_merged" else False
  AttributeError: 'MergeRequest' object has no attribute 'merge_status'

This change adds the merge_status and other missing attributes to the
MergeRequest's __init__() and the de/serialize methods.

Change-Id: I3591017d036304281da87f17f9f0c91fc751bb4f