Fail fast on invalid cross-project dependencies
In some environments, cross-project dependencies can cause
zuul to break with the following exception repeated continuously
in the log files:

2015-06-12 12:42:50,079 ERROR zuul.WebApp: Exception formatting status:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/zuul/webapp.py", line 104, in app
    self.cache = self.scheduler.formatStatusJSON()
  File "/usr/local/lib/python2.7/dist-packages/zuul/scheduler.py", line 974, in formatStatusJSON
    pipelines.append(pipeline.formatStatusJSON())
  File "/usr/local/lib/python2.7/dist-packages/zuul/model.py", line 276, in formatStatusJSON
    j_changes.append(e.formatJSON())
  File "/usr/local/lib/python2.7/dist-packages/zuul/model.py", line 738, in formatJSON
    ret['project'] = changeish.project.name
AttributeError: 'NoneType' object has no attribute 'name'

To stop the bleeding, fail fast when the project is not defined.
A more permanent fix is still needed.

Change-Id: I97299ed2089ad005afaf7494168f4ee74f799e82