(WIP) mimic clone when directory exists
Fails cloner tests:

 GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git remote set-head origin --auto
  stderr: 'error: Cannot determine remote HEAD'

Change-Id: Ie9c02871ef237b9539c7919312260a2afd01599d