Pin boto and friends
The new version of boto3, botocore, or moto is causing

  OSError: [Errno 24] Too many open files

in tests.  Pin them until fixed.

Change-Id: I96ced2711fb659d129a2dd856f8b1c689f541105