Fix NoneType ppc exception in freezeJobGraph()
It looks like the recent changes to rework ppc debugging introduced the
following exception:

  Traceback (most recent call last):
    File "/workspace/zuul/manager/__init__.py", line 1297, in prepareItem
      redact_secrets_and_keys=False)
    File "/workspace/zuul/model.py", line 4126, in freezeJobGraph
      fail_fast=ppc.fail_fast,
  AttributeError: 'NoneType' object has no attribute 'fail_fast'

Most probably this exception was introduced by [1] which merged multiple
update calls into a single one, not taking into account that the ppc
might be None at this point.

[1]: https://review.opendev.org/c/zuul/zuul/+/817798

Change-Id: Ia2a9c92efb2237d67f4c8cdbf5928a59c8339995