Handle artifacts on non change types.
It is possible to have artifacts attached to non change types but
previously this resulted in:

  2019-05-15 14:56:57,990 DEBUG zuul.Pipeline.openstack.release: Starting queue processor: release
  2019-05-15 14:56:57,990 DEBUG zuul.Pipeline.openstack.release: Checking for changes needed by <Tag 0x7f315d1816a0 openstack/tripleo-ui creates refs/tags/7.4.10 on 2620fa03c24a0114a144ad01f550f757c59b8d76>:
  2019-05-15 14:56:57,990 DEBUG zuul.Pipeline.openstack.release:   <class 'zuul.model.Tag'> does not support dependencies
  2019-05-15 14:56:57,990 ERROR zuul.Scheduler: Exception in run handler:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.5/dist-packages/zuul/scheduler.py", line 1025, in run
      while (pipeline.manager.processQueue() and
    File "/usr/local/lib/python3.5/dist-packages/zuul/manager/__init__.py", line 787, in processQueue
      item, nnfi)
    File "/usr/local/lib/python3.5/dist-packages/zuul/manager/__init__.py", line 743, in _processOneItem
      if ready and self.executeJobs(item):
    File "/usr/local/lib/python3.5/dist-packages/zuul/manager/__init__.py", line 416, in executeJobs
      item.pipeline.tenant.semaphore_handler)
    File "/usr/local/lib/python3.5/dist-packages/zuul/model.py", line 2439, in findJobsToRun
      job.updateParentData(parent_build)
    File "/usr/local/lib/python3.5/dist-packages/zuul/model.py", line 1432, in updateParentData
      'change': str(change.number),
  AttributeError: 'Tag' object has no attribute 'number'

Improve updateParentData() so that it attached parent data appropriate
for the ref type.

Change-Id: I6f5fc965b2059d04f9880ce69b3ed324f88a4eb0