Retry queries for commits
When a pull_request event arrives we also get the commit statuses
which are attached to the commit object. Sometimes the commit is not
yet queryable and we get a 404 [1]. In this case we need to retry the
query. In the future we probably want to use that as a feedback
mechanism of a dynamic event delay.

[1] Trace
2018-06-13 11:49:11,881 ERROR zuul.GithubEventConnector: Exception moving GitHub event:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/zuul/driver/github/githubconnection.py", line 391, in run
    self._handleEvent()
  File "/usr/lib/python3.6/site-packages/zuul/driver/github/githubconnection.py", line 226, in _handleEvent
    refresh=True)
  File "/usr/lib/python3.6/site-packages/zuul/driver/github/githubconnection.py", line 751, in _getChange
    self._updateChange(change)
  File "/usr/lib/python3.6/site-packages/zuul/driver/github/githubconnection.py", line 837, in _updateChange
    change.patchset)
  File "/usr/lib/python3.6/site-packages/zuul/driver/github/githubconnection.py", line 1226, in _get_statuses
    for status in self.getCommitStatuses(project.name, sha):
  File "/usr/lib/python3.6/site-packages/zuul/driver/github/githubconnection.py", line 1171, in getCommitStatuses
    commit = repository.commit(sha)
  File "/usr/lib/python3.6/site-packages/github3/repos/repo.py", line 342, in commit
    json = self._json(self._get(url), 200)
  File "/usr/lib/python3.6/site-packages/github3/models.py", line 156, in _json
    raise exceptions.error_for(response)
github3.exceptions.NotFoundError: 404 Not Found

Change-Id: I5cc6d95ed18148657d9e5a8d132a8e43f385771d