Revert "Ensure correct cleanup on repo update and reset"
This reverts commit 36452693e4e35a96fdcb8417c9239d5c409839c4 as it seems to cause:
  ValueError: SHA could not be resolved, git returned: b''
when creating heads.

Change-Id: Ie0c559297b8dc0209c2f38fcc07d1785fd5490fc