Pin elasticsearch to <8.0.0
The latest release 8.0.0 of elasticsearch breaks Zuul when using elasticsearch connection

Trace:
...
File "/usr/local/lib/python3.9/dist-packages/zuul/driver/elasticsearch/con>
self.es = Elasticsearch(
TypeError: __init__() got an unexpected keyword argument 'use_ssl'

Change-Id: Idd4cf9d67f60374fa1e8b9a816845829de31e9f1