Fix race in launcher quota failure test
The zuul launcher test_quota_failure test has a cleanup race that can
trigger a test failure. The node request remains valid so zuul may
attempt to process it at the tail end of the test when things are
shutting down. When that happens we get this exception raise by the
launcher:

  Traceback (most recent call last):
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/launcher/server.py", line 1069, in _processNodes
      self._checkNode(node, log)
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/launcher/server.py", line 1176, in _checkNode
      instance = node.create_state_machine.advance()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/driver/aws/awsendpoint.py", line 228, in advance
      self.create_future = self.endpoint._submitCreateInstance(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/zuul/src/opendev.org/zuul/zuul/zuul/driver/aws/awsendpoint.py", line 1355, in _submitCreateInstance
      return self.create_executor.submit(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/concurrent/futures/thread.py", line 167, in submit
      raise RuntimeError('cannot schedule new futures after shutdown')
  RuntimeError: cannot schedule new futures after shutdown

Then later the test case cleanup checks that we don't log any
exceptions, finds the above exception and fails with:

  Traceback (most recent call last):
    File "/home/zuul/src/opendev.org/zuul/zuul/tests/base.py", line 1860, in checkLogs
      self.fail(f"Traceback found in logs: {record.msg}")
    File "/usr/lib/python3.11/unittest/case.py", line 703, in fail
      raise self.failureException(msg)
  AssertionError: Traceback found in logs: [e: 293dd7f87b7641b28788baf59c563f67] [req: 6da19f664eab4c42bb94e9e9609b8e50] Marking node %s as %s

Avoid this race entirely by explicitly deleting the request at the end
of the test case. This should stop further process of the request and
avoid conflict with clean shutdown checks.

Change-Id: Ia36c7f0027cc9205d243d51a041e3b9740715c72