Catch exception when double unregistering merge jobs
Currently double pause fails with an exception [1]. This causes the
executor not to terminate when using 'zuul-executor graceful' if the
executor is already paused or governed. This can be fixed by catching
the KeyError since we can safely ignore this error.

[1] Trace:
ERROR zuul.ExecutorServer: Exception while processing command
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.8/site-packages/zuul/executor/server.py", line 2898, in runCommand
    self.command_map[command]()
  File "/opt/zuul/lib/python3.8/site-packages/zuul/executor/server.py", line 2859, in graceful
    self.pause()
  File "/opt/zuul/lib/python3.8/site-packages/zuul/executor/server.py", line 2847, in pause
    super().pause()
  File "/opt/zuul/lib/python3.8/site-packages/zuul/merger/server.py", line 136, in pause
    self.merger_gearworker.unregister()
  File "/opt/zuul/lib/python3.8/site-packages/zuul/lib/gearworker.py", line 67, in unregister
    self.gearman.unRegisterFunction(job)
  File "/opt/zuul/lib/python3.8/site-packages/gear/__init__.py", line 1941, in unRegisterFunction
    del self.functions[name]
KeyError: b'merger:merge'

Change-Id: I4b1ce8b51087f84dccdf33c7ee364941368e3b8b