[gitlab driver] Handle missing diff_refs attribute
Recently, on a production Zuul acting on projects hosted on gitlab.com,
it has been discovered that a merge requested fetched from the
API (just after Zuul receives the merge request created event) could have
the "diff_refs" attribute set to None.

Leading to the following stacktrace in the logs:

2022-12-14 10:08:47,921 ERROR zuul.GitlabEventConnector: Exception handling Gitlab event:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zuul/driver/gitlab/gitlabconnection.py", line 102, in run
    self.event_queue.election.run(self._run)
  File "/usr/local/lib/python3.8/site-packages/zuul/zk/election.py", line 28, in run
    return super().run(func, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/kazoo/recipe/election.py", line 54, in run
    func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/zuul/driver/gitlab/gitlabconnection.py", line 110, in _run
    self._handleEvent(event)
  File "/usr/local/lib/python3.8/site-packages/zuul/driver/gitlab/gitlabconnection.py", line 246, in _handleEvent
    self.connection._getChange(change_key, refresh=True,
  File "/usr/local/lib/python3.8/site-packages/zuul/driver/gitlab/gitlabconnection.py", line 621, in _getChange
    change = self._change_cache.updateChangeWithRetry(change_key, change,
  File "/usr/local/lib/python3.8/site-packages/zuul/zk/change_cache.py", line 432, in updateChangeWithRetry
    update_func(change)
  File "/usr/local/lib/python3.8/site-packages/zuul/driver/gitlab/gitlabconnection.py", line 619, in _update_change
    self._updateChange(c, event, mr)
  File "/usr/local/lib/python3.8/site-packages/zuul/driver/gitlab/gitlabconnection.py", line 665, in _updateChange
    change.commit_id = change.mr['diff_refs'].get('head_sha')
AttributeError: 'NoneType' object has no attribute 'get'

The attribute "diff_refs" becomes an object (with the expected keys) few
moments later.

In order to avoid this situation, this change adds a mechanism to retry
fetching a MR until it owns some expected fields. In our case only
"diff_refs".

https://docs.gitlab.com/ee/api/merge_requests.html#response

A test is included with that change.

Change-Id: I6f279516728def655acb8933542a02a4dbb3ccb6