Avoid runtime errors in merger server
When iterating over cached merger/build requests we need to create a
copy of the values to avoid RuntimeErrors when the dictionary is
concurrently modified.

2023-07-03 09:32:10,707 ERROR zuul.ExecutorServer: Error in merge thread:
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.10/site-packages/zuul/merger/server.py", line 191, in runMerger
    for merge_request in self.merger_api.next():
  File "/opt/zuul/lib/python3.10/site-packages/zuul/zk/job_request_queue.py", line 248, in next
    for request in self.inState(self.request_class.REQUESTED):
  File "/opt/zuul/lib/python3.10/site-packages/zuul/zk/job_request_queue.py", line 237, in inState
    requests = [
  File "/opt/zuul/lib/python3.10/site-packages/zuul/zk/job_request_queue.py", line 237, in <listcomp>
    requests = [
RuntimeError: dictionary changed size during iteration

Change-Id: Id899022e5829c27c4650c62ccb1d67a583676624