Fix timestamp race occuring on fast systems
Since the subprocess is started before the timestamp is created it can
happen that the subprocess finishes creating the JWT before the
timestamp is created.

Traceback (most recent call last):
  File "/tmp/zuul/tests/unit/test_client.py", line 151, in test_token_generation
    (token['exp'], now))
  File "/tmp/zuul/.tox/py36/lib/python3.6/site-packages/unittest2/case.py", line 702, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true : (1568016146.9831738, 1568015546.1448617)

Change-Id: I9ef56c12ed1be2a6ec168c4a9363125919be44e9