Check for commitMessage on zuul trigger
Gerrit versions prior to 2.8 are not offering that
commitMessage into the gerrit query feedback. This is
causing latest syncs of zuul to crash with:

File ../zuul/trigger/gerrit.py... in _getNeededByFromCommit
result['commitMessage']):
KeyError: 'commitMessage'

Check for the existence of that key before trying to
search entries containing that.

Change-Id: I330bc3b38bfecca4648f3894e152708490539005