reporter: do not expect branch attribute in Tag object
This change fixes reporting of Tag event where the branch attribute was
expected:

File "zuul/scheduler.py", line 383, in onBuildCompleted
    branchname = (build.build_set.item.change.branch.
AttributeError: 'Tag' object has no attribute 'branch'

File "zuul/driver/sql/sqlreporter.py", line 55, in report
    branch=item.change.branch,
AttributeError: 'Tag' object has no attribute 'branch'

Change-Id: I5dbe4663c4d1e341b08a32eedbbcfb775330e881