Reset repo to previous head on .gitmodules error
A badly configured .gitmodules committed to a repo can currently break
zuul by not allowing it to git fetch [1]. There is already logic handling
merge conflicts in .gitmodules by resetting the repo but this is not
enough if the current commit is faulty. Instead fix this by resetting to
an earlier commit.

[1] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zuul/executor/server.py", line 2935, in _innerUpdateLoop
    self.merger.updateRepo(
  File "/usr/local/lib/python3.8/site-packages/zuul/merger/merger.py", line 805, in updateRepo
    repo.reset(zuul_event_id=zuul_event_id, build=build,
  File "/usr/local/lib/python3.8/site-packages/zuul/merger/merger.py", line 397, in reset
    self.update(zuul_event_id=zuul_event_id, build=build)
  File "/usr/local/lib/python3.8/site-packages/zuul/merger/merger.py", line 601, in update
    self._git_fetch(repo, 'origin', zuul_event_id, tags=True, prune=True)
  File "/usr/local/lib/python3.8/site-packages/zuul/merger/merger.py", line 265, in _git_fetch
    repo.git.fetch(remote, ref_to_fetch,
  File "/usr/local/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/git/cmd.py", line 1006, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/lib/python3.8/site-packages/git/cmd.py", line 823, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -f --prune --tags origin
  stderr: 'fatal: bad config line 9 in file /var/lib/zuul/executor-git/.../.gitmodules'

Change-Id: I33f8f5905167ebb95ab58f9ef192359573495927