Don't try to report build w/o buildset to DB
When a build result arrives for a non-current buildset we should skip
the reporting as we can no longer create the reference to the buildset.

Traceback (most recent call last):
  File "/opt/zuul/lib/python3.10/site-packages/zuul/scheduler.py", line 2654, in _doBuildCompletedEvent
    self.sql.reportBuildEnd(
  File "/opt/zuul/lib/python3.10/site-packages/zuul/driver/sql/sqlreporter.py", line 143, in reportBuildEnd
    db_build = self._createBuild(db, build)
  File "/opt/zuul/lib/python3.10/site-packages/zuul/driver/sql/sqlreporter.py", line 180, in _createBuild
    tenant=buildset.item.pipeline.tenant.name, uuid=buildset.uuid)
AttributeError: 'NoneType' object has no attribute 'item'

Change-Id: Iccbe9ab8212fbbfa21cb29b84a17e03ca221d7bd