[gitlab] approvals: fix error with community edition
'approvals_left' key is not present when 'Required Merge Request
Approvals' feature isn't available. With enterprise edition,
'approved' key can not be used since the related value is always true
when 'approvals_required' is equal to zero.

The exception was:

    Traceback (most recent call last):
      File "zuul/driver/gitlab/gitlabconnection.py", line 240, in run
	self._handleEvent()
      File "zuul/driver/gitlab/gitlabconnection.py", line 230, in _handleEvent
	event=event)
      File "driver/gitlab/gitlabconnection.py", line 510, in _getChange
	self._updateChange(change, event)
      File "driver/gitlab/gitlabconnection.py", line 521, in _updateChange
	change.project.name, change.number, event=event)
      File "zuul/driver/gitlab/gitlabconnection.py", line 560, in getMR
	mr['approved'] = mr_approval_status['approvals_left'] == 0
    KeyError: 'approvals_left'

Change-Id: I07303ae3309937046b69afe18e9e183853fd448f