Update patch set 1
Patch Set 1:

After updating to latest commit, it still happened:

Traceback (most recent call last):
  File "zuul/manager/__init__.py", line 787, in _reportItem
    ret = self.sendReport(actions, item)
  File "zuul/manager/__init__.py", line 168, in sendReport
    ret = reporter.report(item)
  File "zuul/driver/sql/sqlreporter.py", line 75, in report
    build.start_time),
TypeError: a float is required

Patch-set: 1