(WIP) mimic clone when directory exists
Fails cloner tests:

 GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git remote set-head origin --auto
  stderr: 'error: Cannot determine remote HEAD'

When trying to clone repositories:

 project/plugin.git
 project.git

The later will cause git clone to exit 128 because /project already
exists.

Change-Id: Ie9c02871ef237b9539c7919312260a2afd01599d