github: log the project name when getBranches fails
When a project doesn't exist, the configuration fails with a TypeError
which is useless for an unexperienced user. Instead we should
explicitly check for 404 and raise a meaningful exception.

[1] Traceback:
[...]
  File "zuul/configloader.py", line 1323, in _getProjectBranches
    tpc.project, tenant))
  File "zuul/driver/github/githubsource.py", line 108, in getProjectBranches
    return self.connection.getProjectBranches(project, tenant)
  File "zuul/driver/github/githubconnection.py", line 954, in getProjectBranches
    branches.extend([x['name'] for x in resp.json()])
  File "zuul/driver/github/githubconnection.py", line 954, in <listcomp>
    branches.extend([x['name'] for x in resp.json()])
TypeError: string indices must be integers

Change-Id: I4585f15c1f63261d3a2c75c6be633b04a6f24e1c
Co-Authored-By: Tobias Henkel <tobias.henkel@bmw.de>