Replace use of ProjectContext with SourceContext
It seems we never added serialization for ProjectContext objects. This
issue showed up after I3ed9a98dfc1ed63ac11025eb792c61c9a6414384 since we
use the ProjectContext for reporting errors related to the merge mode.

Since the ProjectContext and SourceContext are almost identical we can
use a SourceContext object with irrelevant fields set to None in places
where we currently use the ProjectContext.

ERROR zuul.Pipeline.tenant.check: [e: ...] Error in dynamic layout
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.10/site-packages/zuul/manager/__init__.py", line 1136, in _loadDynamicLayout
    item.setConfigErrors(relevant_errors)
  File "/opt/zuul/lib/python3.10/site-packages/zuul/model.py", line 5549, in setConfigErrors
    self.current_build_set.setConfigErrors(errors)
  File "/opt/zuul/lib/python3.10/site-packages/zuul/model.py", line 4129, in setConfigErrors
    el = ConfigurationErrorList.new(self._active_context,
  File "/opt/zuul/lib/python3.10/site-packages/zuul/zk/zkobject.py", line 224, in new
    data = obj._trySerialize(context)
  File "/opt/zuul/lib/python3.10/site-packages/zuul/zk/zkobject.py", line 249, in _trySerialize
    return self.serialize(context)
  File "/opt/zuul/lib/python3.10/site-packages/zuul/model.py", line 289, in serialize
    "errors": [e.serialize() for e in self.errors],
  File "/opt/zuul/lib/python3.10/site-packages/zuul/model.py", line 289, in <listcomp>
    "errors": [e.serialize() for e in self.errors],
  File "/opt/zuul/lib/python3.10/site-packages/zuul/model.py", line 254, in serialize
    "key": self.key.serialize()
  File "/opt/zuul/lib/python3.10/site-packages/zuul/model.py", line 211, in serialize
    "context": self.context and self.context.serialize(),
AttributeError: 'ProjectContext' object has no attribute 'serialize'

Change-Id: I1b48abcd593685c332f3f218e2ed05cbcebfb244