Don't convert frozensets to list during job freeze
The FrozenJob's serialize method will take care of converting the
provides/requires frozensets to a list. The deserialization will convert
it back from a list to a frozenset.

Since we don't run the deserialization when creating a new FrozenJob,
deserialization won't be invoked and provides/requires will be a list.
This can lead to the following exception:

2022-02-03 13:50:39,790 ERROR zuul.Scheduler: Exception in pipeline processing:
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.8/site-packages/zuul/scheduler.py", line 1813, in _process_pipeline
    while not self._stopped and pipeline.manager.processQueue():
  File "/opt/zuul/lib/python3.8/site-packages/zuul/manager/__init__.py", line 1511, in processQueue
    item_changed, nnfi = self._processOneItem(
  File "/opt/zuul/lib/python3.8/site-packages/zuul/manager/__init__.py", line 1406, in _processOneItem
    if ready and self.provisionNodes(item):
  File "/opt/zuul/lib/python3.8/site-packages/zuul/manager/__init__.py", line 776, in provisionNodes
    jobs = item.findJobsToRequest(item.pipeline.tenant.semaphore_handler)
  File "/opt/zuul/lib/python3.8/site-packages/zuul/model.py", line 4659, in findJobsToRequest
    if not self.jobRequirementsReady(job):
  File "/opt/zuul/lib/python3.8/site-packages/zuul/model.py", line 4507, in jobRequirementsReady
    ret = self.item_ahead.providesRequirements(job, data)
  File "/opt/zuul/lib/python3.8/site-packages/zuul/model.py", line 4470, in providesRequirements
    if not item.providesRequirements(job, data,
  File "/opt/zuul/lib/python3.8/site-packages/zuul/model.py", line 4478, in providesRequirements
    if _job.provides.intersection(requirements):
AttributeError: 'list' object has no attribute 'intersection'

Change-Id: Iaf1c720b6b8428da7b71b2477c345515769b039d