Update patch set 2
Patch Set 2:

The url can be a local path too:

 2019-01-15 10:16:08,705 zuul.Scheduler                   ERROR    Exception in management event:
 Traceback (most recent call last):
   File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/scheduler.py", line 1113, in process_management_queue
     self._doReconfigureEvent(event)
   File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/scheduler.py", line 675, in _doReconfigureEvent
     abide = loader.loadConfig(self.unparsed_abide)
   File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/configloader.py", line 1963, in loadConfig
     tenant = self.tenant_parser.fromYaml(abide, conf_tenant)
   File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/configloader.py", line 1344, in fromYaml
     self._getProjectBranches(tenant, tpc)
   File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/configloader.py", line 1392, in _getProjectBranches
     tpc.project, tenant))
   File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/driver/git/gitsource.py", line 58, in getProjectBranches
     return self.connection.getProjectBranches(project, tenant)
   File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/driver/git/gitconnection.py", line 228, in getProjectBranches
     refs = self.lsRemote(project.name)
   File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/zuul/driver/git/gitconnection.py", line 181, in lsRemote
     urllib.parse.urljoin(self.baseurl, project))
   File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/.tox/py36/lib/python3.6/site-packages/git/cmd.py", line 548, in <lambda>
     return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
   File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/.tox/py36/lib/python3.6/site-packages/git/cmd.py", line 1014, in _call_process
     return self.execute(call, **exec_kwargs)
   File "/home/zuul/src/git.openstack.org/openstack-infra/zuul/.tox/py36/lib/python3.6/site-packages/git/cmd.py", line 825, in execute
     raise GitCommandError(command, status, stderr_value, stdout_value) 
 git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
   cmdline: git ls-remote /tmp/tmpf2nh_5lf/zuul-test/common-config
   stderr: 'fatal: '/tmp/tmpf2nh_5lf/zuul-test/common-config' does not appear to be a git repository
 fatal: Could not read from remote repository.

Patch-set: 2
Label: Verified=0