Refresh cached branches in timer driver
The cache maintenance has an inherent data race as it is only
considering changes as relevent that are currently in any pipeline. To
prevent garbage collection of changes for in-flight events, we only
clean up items older than 2h.

Usually the driver will refresh a change when receiving a connection
event. However, this wasn't the case for trigger events created by the
timer driver.

This can lead to a race condition where a cached branch is cleaned up
while a timer triggered item is enqueued.

For consistency all non-change objects (Branch, Tag, Ref) will now be
refreshed in case the refresh flag of `getChange()` is set to True.

2022-01-24 11:31:50,815 ERROR zuul.Scheduler: Exception processing pipeline periodic-xy in tenant foobar
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.8/site-packages/zuul/scheduler.py", line 1786, in process_pipelines
    pipeline.state.refresh(ctx)
  File "/opt/zuul/lib/python3.8/site-packages/zuul/zk/zkobject.py", line 153, in refresh
    self._load(context)
  File "/opt/zuul/lib/python3.8/site-packages/zuul/zk/zkobject.py", line 205, in _load
    self._set(**self.deserialize(data, context))
  File "/opt/zuul/lib/python3.8/site-packages/zuul/model.py", line 690, in deserialize
    queue = ChangeQueue.fromZK(context, queue_path,
  File "/opt/zuul/lib/python3.8/site-packages/zuul/zk/zkobject.py", line 148, in fromZK
    obj._load(context, path=path)
  File "/opt/zuul/lib/python3.8/site-packages/zuul/zk/zkobject.py", line 205, in _load
    self._set(**self.deserialize(data, context))
  File "/opt/zuul/lib/python3.8/site-packages/zuul/model.py", line 944, in deserialize
    item = QueueItem.fromZK(context, item_path,
  File "/opt/zuul/lib/python3.8/site-packages/zuul/zk/zkobject.py", line 148, in fromZK
    obj._load(context, path=path)
  File "/opt/zuul/lib/python3.8/site-packages/zuul/zk/zkobject.py", line 205, in _load
    self._set(**self.deserialize(data, context))
  File "/opt/zuul/lib/python3.8/site-packages/zuul/model.py", line 4093, in deserialize
    change = self.pipeline.manager.resolveChangeReferences(
  File "/opt/zuul/lib/python3.8/site-packages/zuul/manager/__init__.py", line 199, in resolveChangeReferences
    return self.resolveChangeKeys(
  File "/opt/zuul/lib/python3.8/site-packages/zuul/manager/__init__.py", line 211, in resolveChangeKeys
    self._change_cache[change.cache_key] = change
AttributeError: 'NoneType' object has no attribute 'cache_key'
2022-01-24 11:31:50,811 ERROR zuul.Pipeline.foobar.periodic-xy: Unable to resolve change from key <ChangeKey github org/project Branch master None hash=da4e62f669e51a7fbef5db1a9b480b0bd42693a7febffdb47a4eb794faa300a9>

Change-Id: I62f5b816780e244e1426ab8a8871f09379293f3e