[gitlab driver] Remove usage of MR diff_refs attribute
Since recently Gitlab updates the diff_refs attribute of a merge request
asynchronously. This is discussed here:

https://gitlab.com/gitlab-org/gitlab/-/issues/386562

Usage of that attribute is made difficult and this patch removes its
usage.

The change's `base_sha` attribute is not needed to be set for a change as if
not provided the base branch's tip SHA is used by Zuul internally. The
change's `commit_id` attribute is set via the event's `last_commit`
attribute.

2022-12-14 10:08:47,921 ERROR zuul.GitlabEventConnector: Exception
handling Gitlab event:
Traceback (most recent call last):
  File
"/usr/local/lib/python3.8/site-packages/zuul/driver/gitlab/gitlabconnection.py",
line 102, in run
    self.event_queue.election.run(self._run)
  File "/usr/local/lib/python3.8/site-packages/zuul/zk/election.py",
line 28, in run
    return super().run(func, *args, **kwargs)
  File
"/usr/local/lib/python3.8/site-packages/kazoo/recipe/election.py", line
54, in run
    func(*args, **kwargs)
  File
"/usr/local/lib/python3.8/site-packages/zuul/driver/gitlab/gitlabconnection.py",
line 110, in _run
    self._handleEvent(event)
  File
"/usr/local/lib/python3.8/site-packages/zuul/driver/gitlab/gitlabconnection.py",
line 246, in _handleEvent
    self.connection._getChange(change_key, refresh=True,
  File
"/usr/local/lib/python3.8/site-packages/zuul/driver/gitlab/gitlabconnection.py",
line 621, in _getChange
    change = self._change_cache.updateChangeWithRetry(change_key,
change,
  File "/usr/local/lib/python3.8/site-packages/zuul/zk/change_cache.py",
line 432, in updateChangeWithRetry
    update_func(change)
  File
"/usr/local/lib/python3.8/site-packages/zuul/driver/gitlab/gitlabconnection.py",
line 619, in _update_change
    self._updateChange(c, event, mr)
  File
"/usr/local/lib/python3.8/site-packages/zuul/driver/gitlab/gitlabconnection.py",
line 665, in _updateChange
    change.commit_id = change.mr['diff_refs'].get('head_sha')
AttributeError: 'NoneType' object has no attribute 'get'

Change-Id: Ia819291069e7ed1080bcd3916736b6a311706cce