Fix bug in file filter presentation in Zuul UI
Change 916141[1] changed the format of the file filters in Zuul. This
caused a bug in zuul-web when trying to render a JobVariant that
includes file filters:

    Error: Objects are not valid as a React child (found: object with
    keys {regex, negate}). If you meant to render a collection of
    children, use an array instead.

[1]: https://review.opendev.org/c/zuul/zuul/+/916141

Change-Id: I92c6b632a5691630350a48c4267f603f2df85323