Fix testtools requiring unittest2
While building a virtualenv for Zuul I end up with:

  Running setup.py egg_info for package testtools
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "testtools/setup.py", line 10, in <module>
        import testtools
      File "testtools/__init__.py", line 69, in <module>
        from testtools.testcase import (
      File "testtools/testcase.py", line 28, in <module>
        import unittest2 as unittest
    ImportError: No module named unittest2

testtools 1.5.0 setup.py imports unittest2 which is not yet available
for some reason. Adding unittest2 as a dependency just before testtools
fix it.

Change-Id: Ib42b9aa4f2cc74cacff77f0e0d4feba98ab0bbf4