Set default speed_limit and speed_time for the merger
During the cloner execution I get the following error:
http://paste.openstack.org/show/717955/

TypeError: __init__() missing 2 required positional arguments:
'speed_limit' and 'speed_time'

The official documentations says that these two parameters are
defaulted to 1000 and 30 respectively:
https://docs.openstack.org/infra/zuul/admin/components.html#id4
but they are not.

This commit sets the defaults according to the documentation.

Change-Id: I3abf131d119008d9957e488153a705b47a99e964