Handle artifacts created by non change refs
Artifacts processing assumed it was always operating on Change objects
as speculative artifact state only makes sense for speculative Changes.
However, this was not enforced and we would attempt to process artifacts
for refs/branches/tag/etc leading to this exception:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.11/site-packages/zuul/manager/__init__.py", line 1065, in _executeJobs
      self.sched.executor.execute(
    File "/usr/local/lib/python3.11/site-packages/zuul/executor/client.py", line 63, in execute
      params = zuul.executor.common.construct_build_params(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/zuul/executor/common.py", line 97, in construct_build_params
      ) = item.getJobParentData(job)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/zuul/model.py", line 5431, in getJobParentData
      artifact_data = job.artifact_data or self.getArtifactData(job)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/zuul/model.py", line 5414, in getArtifactData
      self.providesRequirements(job, data)
    File "/usr/local/lib/python3.11/site-packages/zuul/model.py", line 5377, in providesRequirements
      'change': change.number,
                ^^^^^^^^^^^^^
  AttributeError: 'Tag' object has no attribute 'number'

Address this by checking that the object type is Change before we handle
artifacts for it. If it isn't a Change we report that there are no
satisfied provides/requires for this dependency by the currently
processed queue item.

Change-Id: I5ba7f30e56fc890847b86ee776e74272ec04046d