zuul.lib.yamlutil: Fix TypeError exception
Fix this exception which occurs when a zuul secret is used:

    ERROR zuul.Pipeline.pilou.periodic-daily: Error freezing job graph for <QueueItem 7bbd0af8e6a34dfa9df37f5023760c4b for <Change 0x7fabb43a75f8 p
    roject: pilou/docker-debian-systemd number: 4 patchset: c7115c60c8ceb0225253bf92bf1d52b605343dc6 updated: 1601046971 state: open> in periodic-daily>
    Traceback (most recent call last):
      File "/usr/local/zuul/lib/python3.7/site-packages/zuul/manager/__init__.py", line 1110, in prepareItem
        item.freezeJobGraph(self.getLayout(item))
      File "/usr/local/zuul/lib/python3.7/site-packages/zuul/model.py", line 2409, in freezeJobGraph
        job_graph = layout.createJobGraph(self, ppc, skip_file_matcher)
      File "/usr/local/zuul/lib/python3.7/site-packages/zuul/model.py", line 5066, in createJobGraph
        self._createJobGraph(item, ppc, ret, skip_file_matcher)
      File "/usr/local/zuul/lib/python3.7/site-packages/zuul/model.py", line 4979, in _createJobGraph
        frozen_job.setBase(self)
      File "/usr/local/zuul/lib/python3.7/site-packages/zuul/model.py", line 1449, in setBase
        self.pre_run = self.freezePlaybooks(self.pre_run, layout)
      File "/usr/local/zuul/lib/python3.7/site-packages/zuul/model.py", line 1646, in freezePlaybooks
        pb.freezeSecrets(layout)
      File "/usr/local/zuul/lib/python3.7/site-packages/zuul/model.py", line 1123, in freezeSecrets
        encrypted_secret_data = secret.serialize()
      File "/usr/local/zuul/lib/python3.7/site-packages/zuul/model.py", line 948, in serialize
        return yaml.encrypted_dump(self.secret_data, default_flow_style=False)
      File "/usr/local/zuul/lib/python3.7/site-packages/zuul/lib/yamlutil.py", line 108, in encrypted_dump
        return yaml.dump(data, *args, Dumper=EncryptedDumper, **kwargs)
      File "/usr/local/zuul/lib/python3.7/site-packages/yaml/__init__.py", line 290, in dump
        return dump_all([data], stream, Dumper=Dumper, **kwds)
      File "/usr/local/zuul/lib/python3.7/site-packages/yaml/__init__.py", line 278, in dump_all
        dumper.represent(data)
      File "/usr/local/zuul/lib/python3.7/site-packages/yaml/representer.py", line 28, in represent
        self.serialize(node)
      File "/usr/local/zuul/lib/python3.7/site-packages/yaml/serializer.py", line 54, in serialize
        self.serialize_node(node, None, None)
      File "/usr/local/zuul/lib/python3.7/site-packages/yaml/serializer.py", line 108, in serialize_node
        self.serialize_node(value, node, key)
      File "/usr/local/zuul/lib/python3.7/site-packages/yaml/serializer.py", line 100, in serialize_node
        self.emit(SequenceEndEvent())
      File "/usr/local/zuul/lib/python3.7/site-packages/yaml/emitter.py", line 115, in emit
        self.state()
      File "/usr/local/zuul/lib/python3.7/site-packages/yaml/emitter.py", line 374, in expect_first_block_sequence_item
        return self.expect_block_sequence_item(first=True)
      File "/usr/local/zuul/lib/python3.7/site-packages/yaml/emitter.py", line 384, in expect_block_sequence_item
        self.expect_node(sequence=True)
      File "/usr/local/zuul/lib/python3.7/site-packages/yaml/emitter.py", line 242, in expect_node
        self.process_tag()
      File "/usr/local/zuul/lib/python3.7/site-packages/yaml/emitter.py", line 473, in process_tag
        self.style = self.choose_scalar_style()
      File "/usr/local/zuul/lib/python3.7/site-packages/yaml/emitter.py", line 496, in choose_scalar_style
        self.analysis = self.analyze_scalar(self.event.value)
      File "/usr/local/zuul/lib/python3.7/site-packages/yaml/emitter.py", line 650, in analyze_scalar
        if scalar.startswith('---') or scalar.startswith('...'):
    TypeError: startswith first arg must be bytes or a tuple of bytes, not str

Change-Id: I11a1eb18f0b117de24e8368a75bc4f490f04df00