Fix exception on build started event for noop jobs
Use an empty dictionary for the data of the BuildStartedEvent for noop
jobs instead of passing None. Otherwise the dictionary access will
fail when trying to set the worker info.

2021-05-03 13:20:50,287 zuul.Scheduler  ERROR  Exception in run handler:
Traceback (most recent call last):
  File "/home/westphahl/src/opendev/zuul/zuul/zuul/scheduler.py", line 1186, in run
    self.process_result_queue()
  File "/home/westphahl/src/opendev/zuul/zuul/zuul/scheduler.py", line 1441, in process_result_queue
    self._process_result_event(event)
  File "/home/westphahl/src/opendev/zuul/zuul/zuul/scheduler.py", line 1467, in _process_result_event
    self._doBuildStartedEvent(event)
  File "/home/westphahl/src/opendev/zuul/zuul/zuul/scheduler.py", line 1486, in _doBuildStartedEvent
    self.executor.setWorkerInfo(build, event.data)
  File "/home/westphahl/src/opendev/zuul/zuul/zuul/executor/client.py", line 302, in setWorkerInfo
    build.worker.updateFromData(data)
  File "/home/westphahl/src/opendev/zuul/zuul/zuul/model.py", line 2020, in updateFromData
    self.name = data.get('worker_name', self.name)
AttributeError: 'NoneType' object has no attribute 'get'

Change-Id: I09370e9b69b42cbc2d42f32b3c375c49961a8390