WIP fix exception
2021-07-05 16:29:08,771 zuul.Scheduler                   ERROR    Exception in management event:
Traceback (most recent call last):
  File "/home/safranaerosystemsfcs/zuul/zuul/zuul/scheduler.py", line 1315, in _doEnqueueEvent
    change = project.source.getChange(event, refresh=True)
  File "/home/safranaerosystemsfcs/zuul/zuul/zuul/driver/gerrit/gerritsource.py", line 58, in getChange
    return self.connection.getChange(event, refresh)
  File "/home/safranaerosystemsfcs/zuul/zuul/zuul/driver/gerrit/gerritconnection.py", line 753, in getChange
    change = self._getChange(event.change_number, event.patch_number,
  File "/home/safranaerosystemsfcs/zuul/zuul/zuul/driver/gerrit/gerritconnection.py", line 810, in _getChange
    self._updateChange(change, event, history)
  File "/home/safranaerosystemsfcs/zuul/zuul/zuul/driver/gerrit/gerritconnection.py", line 882, in _updateChange
    data = self.queryChange(change.number, event=event)
  File "/home/safranaerosystemsfcs/zuul/zuul/zuul/driver/gerrit/gerritconnection.py", line 1255, in queryChange
    return GerritChangeData(GerritChangeData.SSH, data)
  File "/home/safranaerosystemsfcs/zuul/zuul/zuul/driver/gerrit/gerritconnection.py", line 76, in __init__
    self.parseSSH(data)
  File "/home/safranaerosystemsfcs/zuul/zuul/zuul/driver/gerrit/gerritconnection.py", line 86, in parseSSH
    self.message = data['commitMessage']
KeyError: 'commitMessage'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/safranaerosystemsfcs/zuul/zuul/zuul/scheduler.py", line 1613, in _process_management_event
    self._doEnqueueEvent(event)
  File "/home/safranaerosystemsfcs/zuul/zuul/zuul/scheduler.py", line 1317, in _doEnqueueEvent
    raise ValueError('Unknown change') from exc

Change-Id: If0d12c1bdf412c70b294b684e7ecf9bfd502a8e8