web: encodeURIComponent for zuul-manifest path
This change prevents the following errors when the zuul-manifest contains
percent:

  URIError: Pathname "..." could not be decoded.
  This is likely caused by an invalid percent-encoding.

Change-Id: I62dba8ddd6717c63d427017b03ff912e1fddcb0b