wip: Fix bulk repo state restore
Current assumption is that I2727b00d540ed0d6d650342f427503ddcf5cd533
introduced a regression in that it attempts to restore the repo state of
projects that are not needed. Since the repo wasn't prepared as part of
the Git updates/clones this can lead to job failures.

ERROR zuul.AnsibleJob: [e: ...] [build: ...] Unable to initialize repo for https://******@github.com/org/project
Traceback (most recent call last):
  File "/opt/zuul/lib/python3.11/site-packages/zuul/merger/merger.py", line 122, in __init__
    self._ensure_cloned(zuul_event_id)
  File "/opt/zuul/lib/python3.11/site-packages/zuul/merger/merger.py", line 202, in _ensure_cloned
    self._git_clone(clone_url, zuul_event_id, build=build)
  File "/opt/zuul/lib/python3.11/site-packages/zuul/merger/merger.py", line 284, in _git_clone
    mygit.clone(git.cmd.Git.polish_url(url), self.local_path,
  File "/opt/zuul/lib/python3.11/site-packages/git/cmd.py", line 736, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/git/cmd.py", line 1316, in _call_process
    return self.execute(call, **exec_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zuul/lib/python3.11/site-packages/git/cmd.py", line 1111, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --no-checkout /var/cache/zuul-executor/git/github.com/org/org%2Fproject /var/cache/zuul-executor/jobs/330d8c6be4204a12a460a1d4a8cfbd16/work/src/github.com/org/project
  stderr: 'fatal: repository '/var/cache/zuul-executor/git/github.com/org/org%2Fproject' does not exist'

Change-Id: Ia4a297fb1c30271a9babb25acff4727faf464aa1